site_name: My Docs

theme:
  name: material
  palette:
    scheme: default
  features:
    - search.highlight
    - search.suggest

plugins:
  - search
  - awesome-nav
  - plantuml:
      theme:
        light: catppuccin/latte
        dark: catppuccin/frappe
      puml_url: https://www.plantuml.com/plantuml/
